# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.delete_all
Hwplatform.delete_all
Categoryproject.delete_all
Osplatform.delete_all
Customerlist.delete_all
Bugreason.delete_all
Projectcontrol.delete_all
Categoryfile.delete_all
Status.delete_all
Statussolution.delete_all
user = User.create(email: 'kyle.wang@o2micro.com', password: '12341234', password_confirmation: '12341234', role: 'poweradmin', firstname: 'Kyle', lastname: 'Wang', customerlist_id: '2', visible: 'true', description: 'kyle.wang@O2Micro')
user = User.create(email: 'eason.yuan@o2micro.com', password: '12341234', password_confirmation: '12341234', role: 'admin', firstname: 'Eason', lastname: 'Yuan', customerlist_id: '2', visible: 'true', description: 'eason@yuan@O2Micro')
user = User.create(email: 'francis.hsieh@o2micro.com', password: '12341234', password_confirmation: '12341234', role: 'poweradmin', firstname: 'Francis', lastname: 'Hsieh', customerlist_id: '2', visible: 'true', description: 'francis.hsieh@O2Micro')
user = User.create(email: 'guo.zhu@o2micro.com', password: '12341234', password_confirmation: '12341234', role: 'admin', firstname: 'Guo', lastname: 'Zhu', customerlist_id: '2', visible: 'true', description: 'guo.zhu@O2Micro')
user = User.create(email: 'jim.chang@o2micro.com', password: '12341234', password_confirmation: '12341234', role: 'admin', firstname: 'Jim', lastname: 'Chang', customerlist_id: '2', visible: 'true', description: 'jim.chang@O2Micro')
user = User.create(email: 'jon.chou@o2micro.com', password: '12341234', password_confirmation: '12341234', role: 'admin', firstname: 'Jon', lastname: 'Chou', customerlist_id: '2', visible: 'true', description: 'jon.chou@O2Micro')
user = User.create(email: 'leon.chen@o2micro.com', password: '12341234', password_confirmation: '12341234', role: 'admin', firstname: 'Leon', lastname: 'Chen', customerlist_id: '2', visible: 'true', description: 'leon.chen@O2Micro')
user = User.create(email: 'simon.cheng@o2micro.com', password: '12341234', password_confirmation: '12341234', role: 'member', firstname: 'Simon', lastname: 'Cheng', customerlist_id: '2', visible: 'true', description: 'simon.cheng@O2Micro')
user = User.create(email: 'user.cobra@o2micro.com', password: '886225459095', password_confirmation: '886225459095', role: 'user', firstname: 'Cobra', lastname: 'Cobra', customerlist_id: '2', visible: 'false', description: 'defualt user')
user = User.create(email: 'member.cobra@o2micro.com', password: '886225459095', password_confirmation: '886225459095', role: 'member', firstname: 'Cobra', lastname: 'Cobra', customerlist_id: '2', visible: 'false', description: 'default member')
user = User.create(email: 'admin.cobra@o2micro.com', password: '886225459095', password_confirmation: '886225459095', role: 'admin', firstname: 'Cobra', lastname: 'Cobra', customerlist_id: '2', visible: 'false', description: 'default admin')
hwplatform = Hwplatform.create(hwnickname: 'N/A', hwcode: 'N/A', hwdescription: 'management', hwmajorversion: '', hwminorversion: '', hworder: '1')
hwplatform = Hwplatform.create(hwnickname: 'Wooycow', hwcode: 'OZ890', hwdescription: '5~13-serieses protection IC', hwmajorversion: 'C', hwminorversion: '0', hworder: '10')
hwplatform = Hwplatform.create(hwnickname: 'Mid-Wooycow', hwcode: 'OZ8920', hwdescription: '6~-8-serieses protection IC', hwmajorversion: 'B', hwminorversion: '2', hworder: '12')
hwplatform = Hwplatform.create(hwnickname: 'Little-Wooycow', hwcode: 'OZ8930', hwdescription: '3~6-serieses protection IC', hwmajorversion: 'B', hwminorversion: '4', hworder: '13')
hwplatform = Hwplatform.create(hwnickname: 'Wooybull', hwcode: 'OZ8940', hwdescription: '6~12-serieses protection IC', hwmajorversion: 'B', hwminorversion: '0', hworder: '14')
hwplatform = Hwplatform.create(hwnickname: 'LanyangII', hwcode: 'OZ8806', hwdescription: '1 cell monitor IC', hwmajorversion: 'C', hwminorversion: '0', hworder: '20')
hwplatform = Hwplatform.create(hwnickname: 'Azalea5', hwcode: 'OZ3705', hwdescription: '5-serieses Monitor IC', hwmajorversion: 'A', hwminorversion: '1', hworder: '30')
hwplatform = Hwplatform.create(hwnickname: 'Azalea10', hwcode: 'OZ3710', hwdescription: '10-serieses Monitor IC', hwmajorversion: 'A', hwminorversion: '1', hworder: '31')
hwplatform = Hwplatform.create(hwnickname: 'Azalea15', hwcode: 'OZ3715', hwdescription: '15-serieses Monitor IC', hwmajorversion: 'A', hwminorversion: '1', hworder: '32')
hwplatform = Hwplatform.create(hwnickname: 'Azalea17', hwcode: 'Azalea17', hwdescription: '17-serieses Monitor chip', hwmajorversion: 'A', hwminorversion: '1', hworder: '33')
hwplatform = Hwplatform.create(hwnickname: 'Bluewhale', hwcode: 'OZ1C115', hwdescription: '1 cell monitor IC and charger', hwmajorversion: 'A', hwminorversion: '1', hworder: '21')
hwplatform = Hwplatform.create(hwnickname: 'OZ1C115C', hwcode: 'OZ1C115C', hwdescription: '1 cell monitor IC and charger', hwmajorversion: 'A', hwminorversion: '1', hworder: '22')
hwplatform = Hwplatform.create(hwnickname: 'KallV', hwcode: 'OZ7705', hwdescription: '3~5-series protection IC', hwmajorversion: 'A', hwminorversion: '0', hworder: '40')
hwplatform = Hwplatform.create(hwnickname: 'Kall10', hwcode: 'Kall10', hwdescription: '5~10-series protection IC', hwmajorversion: 'A', hwminorversion: '0', hworder: '41')
hwplatform = Hwplatform.create(hwnickname: 'Kall14', hwcode: 'Kall14', hwdescription: '7~14-series protection IC', hwmajorversion: 'A', hwminorversion: '0', hworder: '42')
hwplatform = Hwplatform.create(hwnickname: 'MerlionPD', hwcode: 'MerlionPD', hwdescription: 'USB PD IC', hwmajorversion: 'A', hwminorversion: '0', hworder: '50')
hwplatform = Hwplatform.create(hwnickname: 'BaracudaII', hwcode: 'OZ9313', hwdescription: 'micro processor', hwmajorversion: 'C', hwminorversion: '5', hworder: '100')
hwplatform = Hwplatform.create(hwnickname: 'OZ9313+OZ890', hwcode: 'OZ9313+OZ890', hwdescription: 'OZ9313+OZ890', hwmajorversion: 'C', hwminorversion: '5', hworder: '101')
hwplatform = Hwplatform.create(hwnickname: 'OZ9313+OZ8920', hwcode: 'OZ9313+OZ8920', hwdescription: 'OZ9313+OZ8920', hwmajorversion: 'C', hwminorversion: '5', hworder: '102')
hwplatform = Hwplatform.create(hwnickname: 'OZ9313+OZ8930', hwcode: 'OZ9313+OZ8930', hwdescription: 'OZ9313+OZ8930', hwmajorversion: 'C', hwminorversion: '5', hworder: '103')
hwplatform = Hwplatform.create(hwnickname: 'OZ9313+OZ8940', hwcode: 'OZ9313+OZ8940', hwdescription: 'OZ9313+OZ8940', hwmajorversion: 'C', hwminorversion: '5', hworder: '104')
hwplatform = Hwplatform.create(hwnickname: 'OZ9313+OZ3710', hwcode: 'OZ9313+OZ3710', hwdescription: 'OZ9313+OZ3710', hwmajorversion: 'C', hwminorversion: '5', hworder: '105')
categoryproject = Categoryproject.create(categoryprojectstring: 'Software Project', categoryprojectorder: '1')
categoryproject = Categoryproject.create(categoryprojectstring: 'Firmware Project', categoryprojectorder: '2')
categoryproject = Categoryproject.create(categoryprojectstring: 'Driver Project', categoryprojectorder: '3')
categoryproject = Categoryproject.create(categoryprojectstring: 'Management Project', categoryprojectorder: '10')
osplatform = Osplatform.create(categoryproject_id: '1', osdescribe: 'All Windows 32/64', osorder: '1')
osplatform = Osplatform.create(categoryproject_id: '1', osdescribe: 'All Windows 32-bit', osorder: '10')
osplatform = Osplatform.create(categoryproject_id: '1', osdescribe: 'All Windows 64-bit', osorder: '11')
osplatform = Osplatform.create(categoryproject_id: '1', osdescribe: 'Windows XP', osorder: '20')
osplatform = Osplatform.create(categoryproject_id: '1', osdescribe: 'Windows Vista/32', osorder: '21')
osplatform = Osplatform.create(categoryproject_id: '1', osdescribe: 'Windows Vista/64', osorder: '22')
osplatform = Osplatform.create(categoryproject_id: '1', osdescribe: 'Windows 7/32', osorder: '23')
osplatform = Osplatform.create(categoryproject_id: '1', osdescribe: 'Windows 7/64', osorder: '24')
osplatform = Osplatform.create(categoryproject_id: '1', osdescribe: 'Windows 8/32', osorder: '25')
osplatform = Osplatform.create(categoryproject_id: '1', osdescribe: 'Windows 8/64', osorder: '26')
osplatform = Osplatform.create(categoryproject_id: '1', osdescribe: 'Windows 10/32', osorder: '27')
osplatform = Osplatform.create(categoryproject_id: '1', osdescribe: 'Windows 10/64', osorder: '28')
osplatform = Osplatform.create(categoryproject_id: '1', osdescribe: 'Android', osorder: '50')
osplatform = Osplatform.create(categoryproject_id: '1', osdescribe: 'iPhone', osorder: '51')
osplatform = Osplatform.create(categoryproject_id: '2', osdescribe: 'OZ9313+AFE', osorder: '100')
osplatform = Osplatform.create(categoryproject_id: '2', osdescribe: 'OZ9320', osorder: '101')
osplatform = Osplatform.create(categoryproject_id: '2', osdescribe: 'USBtoI2C adaptor', osorder: '102')
osplatform = Osplatform.create(categoryproject_id: '3', osdescribe: 'All Windows 32/64', osorder: '200')
osplatform = Osplatform.create(categoryproject_id: '3', osdescribe: 'Windows 32 bit', osorder: '201')
osplatform = Osplatform.create(categoryproject_id: '3', osdescribe: 'Windows 64 bit', osorder: '202')
osplatform = Osplatform.create(categoryproject_id: '3', osdescribe: 'All Android', osorder: '210')
osplatform = Osplatform.create(categoryproject_id: '3', osdescribe: 'Other(s)', osorder: '220')
osplatform = Osplatform.create(categoryproject_id: '4', osdescribe: 'Management', osorder: '300')
customerlist = Customerlist.create(companyname: 'O2Micro', customerorder:1,companydescription: 'O2Micro G807', engineeremail: 'francis.kk@o2micro.com')
customerlist = Customerlist.create(companyname: 'O2Micro', customerorder:2,companydescription: 'O2Micro G803', engineeremail: 'francis.oo@o2micro.com')
customerlist = Customerlist.create(companyname: 'O2Micro', customerorder:3,companydescription: 'O2Micro G851', engineeremail: 'francis.mm@o2micro.com')
customerlist = Customerlist.create(companyname: 'O2Micro', customerorder:4,companydescription: 'O2Micro G806', engineeremail: 'francis.dd@o2micro.com')
customerlist = Customerlist.create(companyname: 'O2Micro', customerorder:5,companydescription: 'O2Micro G809', engineeremail: 'adaptor.hsieh@o2micro.com')
customerlist = Customerlist.create(companyname: 'O2Micro', customerorder:6,companydescription: 'O2Micro G801', engineeremail: 'bb.hsieh@o2micro.com')
customerlist = Customerlist.create(companyname: 'O2Micro', customerorder:7,companydescription: 'O2Micro G836', engineeremail: 'cc.hsieh@o2micro.com')
customerlist = Customerlist.create(companyname: 'O2Micro', customerorder:8,companydescription: 'O2Micro G833', engineeremail: 'dd.hsieh@o2micro.com')
customerlist = Customerlist.create(companyname: 'O2Micro', customerorder:9,companydescription: 'O2Micro G838', engineeremail: 'ee.hsieh@o2micro.com')
customerlist = Customerlist.create(companyname: 'O2Micro', customerorder:10,companydescription: 'O2Micro G839', engineeremail: 'ff.hsieh@o2micro.com')

bugreason = Bugreason.create(bugdescriptionstring: 'Task-Team task', bugorder: '1')
bugreason = Bugreason.create(bugdescriptionstring: 'Task-Project task', bugorder: '2')
bugreason = Bugreason.create(bugdescriptionstring: 'Task-Customer Requirement', bugorder: '3')
bugreason = Bugreason.create(bugdescriptionstring: 'Task-Customer Spec Change', bugorder: '4')
bugreason = Bugreason.create(bugdescriptionstring: 'Task-Product Spec Change', bugorder: '5')
bugreason = Bugreason.create(bugdescriptionstring: 'Bug-R&D', bugorder: '10')
bugreason = Bugreason.create(bugdescriptionstring: 'Bug-Test Team', bugorder: '11')
bugreason = Bugreason.create(bugdescriptionstring: 'Bug-FAE', bugorder: '12')
bugreason = Bugreason.create(bugdescriptionstring: 'Bug-Customer', bugorder: '13')
bugreason = Bugreason.create(bugdescriptionstring: 'Solution Sync', bugorder: '20')
categoryfile = Categoryfile.create(categoryfilestring: 'Installation File', categoryfileorder: '1')
categoryfile = Categoryfile.create(categoryfilestring: 'Executable File', categoryfileorder: '2')
categoryfile = Categoryfile.create(categoryfilestring: 'Zipped File', categoryfileorder: '3')
categoryfile = Categoryfile.create(categoryfilestring: 'Document/text File', categoryfileorder: '4')
categoryfile = Categoryfile.create(categoryfilestring: 'Cobra OCE File', categoryfileorder: '5')
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?

projectcontrol = Projectcontrol.create(projectname: '[SW][Cobra]', projectcode: 'SWUCOBRA', categoryproject_id: '1', osplatform_id: '1', hwplatform_id: '1', status_id: '1', customerlist_id: '2', assignedto_id: '3', reporter_id: '1', prjdescription:'create project',statussolution_id:'3')
projectcontrol = Projectcontrol.create(projectname: '[SW][Cobra OCE][OZ3705][X]', projectcode: 'OCE3705X', categoryproject_id: '1', osplatform_id: '1', hwplatform_id: '7', status_id: '1', customerlist_id: '2', assignedto_id: '4', reporter_id: '3', prjdescription:'create project',statussolution_id:'2')
projectcontrol = Projectcontrol.create(projectname: '[SW][Cobra OCE][OZ3705][Y]', projectcode: 'OCE3705Y', categoryproject_id: '1', osplatform_id: '1', hwplatform_id: '7', status_id: '1', customerlist_id: '2', assignedto_id: '4', reporter_id: '3', prjdescription:'create project',statussolution_id:'1')
projectcontrol = Projectcontrol.create(projectname: '[SW][Cobra OCE][OZ3710][X]', projectcode: 'OCE3710X', categoryproject_id: '1', osplatform_id: '1', hwplatform_id: '8', status_id: '1', customerlist_id: '2', assignedto_id: '5', reporter_id: '6', prjdescription:'create project',statussolution_id:'4')
projectcontrol = Projectcontrol.create(projectname: '[SW][Cobra OCE][OZ3710][Y]', projectcode: 'OCE3710Y', categoryproject_id: '1', osplatform_id: '1', hwplatform_id: '8', status_id: '1', customerlist_id: '2', assignedto_id: '5', reporter_id: '6', prjdescription:'create project',statussolution_id:'5')
projectcontrol = Projectcontrol.create(projectname: '[SW][Cobra OCE][OZ3715][X]', projectcode: 'OCE3715X', categoryproject_id: '1', osplatform_id: '1', hwplatform_id: '9', status_id: '1', customerlist_id: '2', assignedto_id: '6', reporter_id: '7', prjdescription:'create project',statussolution_id:'1')
projectcontrol = Projectcontrol.create(projectname: '[SW][Cobra OCE][OZ3715][Y]', projectcode: 'OCE3715Y', categoryproject_id: '1', osplatform_id: '1', hwplatform_id: '9', status_id: '1', customerlist_id: '2', assignedto_id: '6', reporter_id: '7', prjdescription:'create project',statussolution_id:'2')
projectcontrol = Projectcontrol.create(projectname: '[SW][Cobra OCE][KallV][X]', projectcode: 'OCEKALVX', categoryproject_id: '1', osplatform_id: '1', hwplatform_id: '13', status_id: '1', customerlist_id: '2', assignedto_id: '3', reporter_id: '4', prjdescription:'create project',statussolution_id:'4')
projectcontrol = Projectcontrol.create(projectname: '[SW][Cobra OCE][KallV][Y]', projectcode: 'OCEKALVY', categoryproject_id: '1', osplatform_id: '1', hwplatform_id: '13', status_id: '1', customerlist_id: '2', assignedto_id: '3', reporter_id: '4', prjdescription:'create project',statussolution_id:'3')
projectcontrol = Projectcontrol.create(projectname: '[SW][Cobra OCE][Kall10][X]', projectcode: 'OCECKL10X', categoryproject_id: '1', osplatform_id: '1', hwplatform_id: '14', status_id: '1', customerlist_id: '2', assignedto_id: '7', reporter_id: '2', prjdescription:'create project',statussolution_id:'1')
projectcontrol = Projectcontrol.create(projectname: '[SW][Cobra OCE][Kall10][Y]', projectcode: 'OCECKL10Y', categoryproject_id: '1', osplatform_id: '1', hwplatform_id: '14', status_id: '1', customerlist_id: '2', assignedto_id: '7', reporter_id: '2', prjdescription:'create project',statussolution_id:'5')
projectcontrol = Projectcontrol.create(projectname: '[DR][Andriod][OZ1C115][O2Micro]', projectcode: 'DRANC115', categoryproject_id: '3', osplatform_id: '20', hwplatform_id: '11', status_id: '1', customerlist_id: '2', assignedto_id: '2', reporter_id: '2', prjdescription:'create project',statussolution_id:'2')
projectcontrol = Projectcontrol.create(projectname: '[DR][Andriod][OZ1C115C][O2Micro]', projectcode: 'DRAN115C', categoryproject_id: '3', osplatform_id: '20', hwplatform_id: '12', status_id: '1', customerlist_id: '2', assignedto_id: '2', reporter_id: '2', prjdescription:'create project',statussolution_id:'3')
projectcontrol = Projectcontrol.create(projectname: '[FW][FalconLY][New Gas Gauge][O2Micro]', projectcode: 'FWGGFLCN', categoryproject_id: '2', osplatform_id: '22', hwplatform_id: '13', status_id: '1', customerlist_id: '2', assignedto_id: '6', reporter_id: '2', prjdescription:'create project',statussolution_id:'4')


status = Status.create(statusstring: 'ASSIGNED', statusorder: '01', statusproject: 'true', statusissue: 'true', statusrelease: 'true')
status = Status.create(statusstring: 'SOLVED', statusorder: '52', statusproject: 'true', statusissue: 'true', statusrelease: 'false')
status = Status.create(statusstring: 'LATER', statusorder: '53', statusproject: 'true', statusissue: 'true', statusrelease: 'true')
status = Status.create(statusstring: 'INVALID', statusorder: '54', statusproject: 'true', statusissue: 'true', statusrelease: 'true')
status = Status.create(statusstring: 'WONTFIXED', statusorder: '55', statusproject: 'false', statusissue: 'true', statusrelease: 'false')
status = Status.create(statusstring: 'REOPENED', statusorder: '81', statusproject: 'true', statusissue: 'true', statusrelease: 'false')
status = Status.create(statusstring: 'CLOSED', statusorder: '98', statusproject: 'true', statusissue: 'true', statusrelease: 'true')
status = Status.create(statusstring: 'APPROVED', statusorder: '99', statusproject: 'false', statusissue: 'false', statusrelease: 'true')
statussolution = Statussolution.create(status_id: '1', solutionstring: 'N/A', solutionorder: '11')
statussolution = Statussolution.create(status_id: '2', solutionstring: 'N/A', solutionorder: '21')
statussolution = Statussolution.create(status_id: '2', solutionstring: 'FIXED', solutionorder: '22')
statussolution = Statussolution.create(status_id: '2', solutionstring: 'LATER', solutionorder: '23')
statussolution = Statussolution.create(status_id: '2', solutionstring: 'INVALID', solutionorder: '24')
statussolution = Statussolution.create(status_id: '2', solutionstring: 'WONTFIXED', solutionorder: '25')
#statussolution = Statussolution.create(status_id: '7', solutionstring: 'N/A', solutionorder: '71')
#statussolution = Statussolution.create(status_id: '8', solutionstring: 'N/A', solutionorder: '81')
